#!/bin/bash

if [ "$USER_NAME" == "shravan" ]; then 
    echo "valid SECRET"
else
    echo "invalid SECRET"
fi

if [ "$USER_ADMIN" == "shravank" ]; then 
    echo "valid VARIABLE"
else
    echo "invalid VARIABLE"
fi
